//
// ActiveTrack.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActiveTrack: Codable {

    public var artist: String?
    public var title: String
    public var album: String?
    public var albumArtURI: String?
    public var duration: Int
    public var uri: String
    public var radioShowMeta: String?
    public var streamInfo: String?
    public var type: String

    public init(artist: String?, title: String, album: String?, albumArtURI: String?, duration: Int, uri: String, radioShowMeta: String?, streamInfo: String?, type: String) {
        self.artist = artist
        self.title = title
        self.album = album
        self.albumArtURI = albumArtURI
        self.duration = duration
        self.uri = uri
        self.radioShowMeta = radioShowMeta
        self.streamInfo = streamInfo
        self.type = type
    }


}

