//
// AmbientLightDataPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AmbientLightDataPoint: Codable {

    public var timestamp: Date?
    public var data: [String:Double]?

    public init(timestamp: Date?, data: [String:Double]?) {
        self.timestamp = timestamp
        self.data = data
    }


}

