//
// ApiResponse2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApiResponse2: Codable {

    public var code: Int?
    public var message: String?

    public init(code: Int?, message: String?) {
        self.code = code
        self.message = message
    }


}

