//
// DeviceConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceConfig: Codable {

    public var types: [String]?
    public var deviceId: String?
    public var url: String?
    public var _id: String?

    public init(types: [String]?, deviceId: String?, url: String?, _id: String?) {
        self.types = types
        self.deviceId = deviceId
        self.url = url
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case types
        case deviceId
        case url
        case _id = "id"
    }


}

