//
// Device.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Device: Codable {

    public var url: String?
    public var deviceId: String?
    public var _id: String?
    public var name: String?
    public var type: String?
    public var addedAt: Date?
    public var token: UUID?

    public init(url: String?, deviceId: String?, _id: String?, name: String?, type: String?, addedAt: Date?, token: UUID?) {
        self.url = url
        self.deviceId = deviceId
        self._id = _id
        self.name = name
        self.type = type
        self.addedAt = addedAt
        self.token = token
    }

    public enum CodingKeys: String, CodingKey { 
        case url
        case deviceId
        case _id = "id"
        case name
        case type
        case addedAt
        case token
    }


}

