//
// DeviceNotification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceNotification: Codable {

    public var deviceId: String?
    public var notificationType: String?
    public var value: JSONValue?

    public init(deviceId: String?, notificationType: String?, value: JSONValue?) {
        self.deviceId = deviceId
        self.notificationType = notificationType
        self.value = value
    }


}

