//
// ElasticTranscribeConfiguration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ElasticTranscribeConfiguration: Codable {

    public var accessKeyId: String?
    public var secretAccessKey: String?

    public init(accessKeyId: String?, secretAccessKey: String?) {
        self.accessKeyId = accessKeyId
        self.secretAccessKey = secretAccessKey
    }


}

