//
// FavoriteChannel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FavoriteChannel: Codable {

    public var title: String
    public var albumArtURI: String?
    public var uri: String?

    public init(title: String, albumArtURI: String?, uri: String?) {
        self.title = title
        self.albumArtURI = albumArtURI
        self.uri = uri
    }


}

