//
// Forecast.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Forecast: Codable {

    public var date: Date?
    public var pressure: Double?
    public var humidity: Int?
    public var windSpeed: Double?
    public var clouds: Int?
    public var temperature: ForecastTemperature?
    public var weather: WeatherForecast?

    public init(date: Date?, pressure: Double?, humidity: Int?, windSpeed: Double?, clouds: Int?, temperature: ForecastTemperature?, weather: WeatherForecast?) {
        self.date = date
        self.pressure = pressure
        self.humidity = humidity
        self.windSpeed = windSpeed
        self.clouds = clouds
        self.temperature = temperature
        self.weather = weather
    }


}

