//
// ForecastTemperature.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ForecastTemperature: Codable {

    /** the current temperature */
    public var temp: Double?
    /** the expected low */
    public var low: Double?
    /** the expected high */
    public var high: Double?
    public var morning: Double?
    public var day: Double?
    public var evening: Double?
    public var night: Double?

    public init(temp: Double?, low: Double?, high: Double?, morning: Double?, day: Double?, evening: Double?, night: Double?) {
        self.temp = temp
        self.low = low
        self.high = high
        self.morning = morning
        self.day = day
        self.evening = evening
        self.night = night
    }


}

