//
// IrrigationZone.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IrrigationZone: Codable {

    public var _id: String?
    public var name: String?
    public var zoneId: Int?
    public var state: Bool?

    public init(_id: String?, name: String?, zoneId: Int?, state: Bool?) {
        self._id = _id
        self.name = name
        self.zoneId = zoneId
        self.state = state
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case zoneId
        case state
    }


}

