//
// IrrigationSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IrrigationSummary: Codable {

    public var dailyRunTime: RunTime?
    public var zones: [IrrigationZone]?

    public init(dailyRunTime: RunTime?, zones: [IrrigationZone]?) {
        self.dailyRunTime = dailyRunTime
        self.zones = zones
    }


}

