//
// LightingZoneStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LightingZoneStatus: Codable {

    public var _id: String?
    public var name: String?
    public var lastUpdate: Date?
    public var level: String?
    public var zone: String?
    public var rooms: [String]?

    public init(_id: String?, name: String?, lastUpdate: Date?, level: String?, zone: String?, rooms: [String]?) {
        self._id = _id
        self.name = name
        self.lastUpdate = lastUpdate
        self.level = level
        self.zone = zone
        self.rooms = rooms
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case lastUpdate
        case level
        case zone
        case rooms
    }


}

