//
// LoggersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoggersResponse: Codable {

    public var loggers: [String]?

    public init(loggers: [String]?) {
        self.loggers = loggers
    }


}

