//
// OpenWeatherConfiguration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OpenWeatherConfiguration: Codable {

    public var apiKey: String?

    public init(apiKey: String?) {
        self.apiKey = apiKey
    }


}

