//
// PlayerVolume.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlayerVolume: Codable {

    public var volume: Int?

    public init(volume: Int?) {
        self.volume = volume
    }


}

