//
// Schedule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Schedule: Codable {

    public var _id: String?
    public var when: [JSONValue]?
    public var then: [JSONValue]?
    public var until: JSONValue?
    public var finally: [JSONValue]?

    public init(_id: String?, when: [JSONValue]?, then: [JSONValue]?, until: JSONValue?, finally: [JSONValue]?) {
        self._id = _id
        self.when = when
        self.then = then
        self.until = until
        self.finally = finally
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case when
        case then
        case until
        case finally
    }


}

