//
// SoundZoneStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** status of a single sound zone */

public struct SoundZoneStatus: Codable {

    public var _id: String?
    public var name: String?
    public var address: String?
    public var currentTrack: ActiveTrack?
    public var status: String?
    public var volume: Int?
    public var currentPlayMode: String?
    public var nextTrack: Track?
    public var relTime: Int?
    public var stateTime: Int64?
    public var mute: Bool?
    public var trackNo: Int?
    public var currentState: String?
    public var zone: String?
    public var rooms: [String]?

    public init(_id: String?, name: String?, address: String?, currentTrack: ActiveTrack?, status: String?, volume: Int?, currentPlayMode: String?, nextTrack: Track?, relTime: Int?, stateTime: Int64?, mute: Bool?, trackNo: Int?, currentState: String?, zone: String?, rooms: [String]?) {
        self._id = _id
        self.name = name
        self.address = address
        self.currentTrack = currentTrack
        self.status = status
        self.volume = volume
        self.currentPlayMode = currentPlayMode
        self.nextTrack = nextTrack
        self.relTime = relTime
        self.stateTime = stateTime
        self.mute = mute
        self.trackNo = trackNo
        self.currentState = currentState
        self.zone = zone
        self.rooms = rooms
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case address
        case currentTrack
        case status
        case volume
        case currentPlayMode
        case nextTrack
        case relTime
        case stateTime
        case mute
        case trackNo
        case currentState
        case zone
        case rooms
    }


}

