//
// TemperatureZone.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemperatureZone: Codable {

    /** the unique identifier for the zone */
    public var _id: String
    public var name: String
    public var inputPosition: Int?
    public var outputPosition: Int?
    public var zone: String?

    public init(_id: String, name: String, inputPosition: Int?, outputPosition: Int?, zone: String?) {
        self._id = _id
        self.name = name
        self.inputPosition = inputPosition
        self.outputPosition = outputPosition
        self.zone = zone
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case inputPosition
        case outputPosition
        case zone
    }


}

