//
// TemperatureZoneItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemperatureZoneItem: Codable {

    public enum Heater: String, Codable { 
        case on = "on"
        case off = "off"
    }
    public var timestamp: Date?
    public var heater: Heater?
    public var temperature: Double?

    public init(timestamp: Date?, heater: Heater?, temperature: Double?) {
        self.timestamp = timestamp
        self.heater = heater
        self.temperature = temperature
    }


}

