//
// TemperatureSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemperatureSummary: Codable {

    public var zones: [TemperatureZone]?
    public var zoneStatus: [TemperatueZoneStatus]?

    public init(zones: [TemperatureZone]?, zoneStatus: [TemperatueZoneStatus]?) {
        self.zones = zones
        self.zoneStatus = zoneStatus
    }


}

