//
// TemperatureZoneHistoryItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemperatureZoneHistoryItem: Codable {

    public enum Heater: String, Codable { 
        case on = "on"
        case off = "off"
    }
    public var timestamp: Date?
    public var temperature: Double?
    public var heater: Heater?
    public var setPoint: Double?

    public init(timestamp: Date?, temperature: Double?, heater: Heater?, setPoint: Double?) {
        self.timestamp = timestamp
        self.temperature = temperature
        self.heater = heater
        self.setPoint = setPoint
    }


}

