//
// Track.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Track: Codable {

    public var title: String
    public var uri: String
    public var albumArtURI: String
    public var artist: String
    public var album: String

    public init(title: String, uri: String, albumArtURI: String, artist: String, album: String) {
        self.title = title
        self.uri = uri
        self.albumArtURI = albumArtURI
        self.artist = artist
        self.album = album
    }


}

