//
// WeatherForecast.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WeatherForecast: Codable {

    public var summary: String?
    public var _description: String?
    public var icon: String?

    public init(summary: String?, _description: String?, icon: String?) {
        self.summary = summary
        self._description = _description
        self.icon = icon
    }

    public enum CodingKeys: String, CodingKey { 
        case summary
        case _description = "description"
        case icon
    }


}

