//
// ActiveTrack.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ActiveTrack: JSONEncodable {

    public var artist: String?
    public var title: String?
    public var album: String?
    public var albumArtURI: String?
    public var duration: Int32?
    public var uri: String?
    public var radioShowMeta: String?
    public var streamInfo: String?
    public var type: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["artist"] = self.artist
        nillableDictionary["title"] = self.title
        nillableDictionary["album"] = self.album
        nillableDictionary["albumArtURI"] = self.albumArtURI
        nillableDictionary["duration"] = self.duration?.encodeToJSON()
        nillableDictionary["uri"] = self.uri
        nillableDictionary["radioShowMeta"] = self.radioShowMeta
        nillableDictionary["streamInfo"] = self.streamInfo
        nillableDictionary["type"] = self.type

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

