//
// DeviceRegistrationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceRegistrationRequest: Codable {

    public var name: String?
    public var _id: String?
    public var url: String?
    public var deviceId: String?
    public var types: [String]?

    public init(name: String?, _id: String?, url: String?, deviceId: String?, types: [String]?) {
        self.name = name
        self._id = _id
        self.url = url
        self.deviceId = deviceId
        self.types = types
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _id = "id"
        case url
        case deviceId
        case types
    }


}

