//
// Device.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Device: JSONEncodable {

    public var url: String?
    public var deviceId: String?
    public var id: String?
    public var name: String?
    public var type: String?
    public var addedAt: Date?
    public var token: UUID?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["url"] = self.url
        nillableDictionary["deviceId"] = self.deviceId
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["type"] = self.type
        nillableDictionary["addedAt"] = self.addedAt?.encodeToJSON()
        nillableDictionary["token"] = self.token?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

