//
// DeviceRegistrationInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class DeviceRegistrationInfo: JSONEncodable {

    public var url: String?
    public var id: String?
    public var types: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["url"] = self.url
        nillableDictionary["id"] = self.id
        nillableDictionary["types"] = self.types?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

