//
// ForecastTemperature.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ForecastTemperature: JSONEncodable {

    /** the current temperature */
    public var temp: Double?
    /** the expected low */
    public var low: Double?
    /** the expected high */
    public var high: Double?
    public var morning: Double?
    public var day: Double?
    public var evening: Double?
    public var night: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["temp"] = self.temp
        nillableDictionary["low"] = self.low
        nillableDictionary["high"] = self.high
        nillableDictionary["morning"] = self.morning
        nillableDictionary["day"] = self.day
        nillableDictionary["evening"] = self.evening
        nillableDictionary["night"] = self.night

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

