//
// LightingZone.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class LightingZone: JSONEncodable {

    public enum DeviceType: String { 
        case dimmer = "dimmer"
        case _switch = "switch"
        case remote = "remote"
    }
    public var id: String?
    public var name: String?
    public var deviceId: Int32?
    public var deviceType: DeviceType?
    public var zone: String?
    public var rooms: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["deviceId"] = self.deviceId?.encodeToJSON()
        nillableDictionary["deviceType"] = self.deviceType?.rawValue
        nillableDictionary["zone"] = self.zone
        nillableDictionary["rooms"] = self.rooms?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

