//
// LightingZoneStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class LightingZoneStatus: JSONEncodable {

    public var id: String?
    public var name: String?
    public var lastUpdate: Date?
    public var level: String?
    public var zone: String?
    public var rooms: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["lastUpdate"] = self.lastUpdate?.encodeToJSON()
        nillableDictionary["level"] = self.level
        nillableDictionary["zone"] = self.zone
        nillableDictionary["rooms"] = self.rooms?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

