//
// Schedule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Schedule: JSONEncodable {

    public var when: [Any]?
    public var then: [Any]?
    public var until: Any?
    public var finally: [Any]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["when"] = self.when?.encodeToJSON()
        nillableDictionary["then"] = self.then?.encodeToJSON()
        nillableDictionary["until"] = self.until
        nillableDictionary["finally"] = self.finally?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

