//
// Sensor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Sensor: JSONEncodable {

    public enum ModelType: String { 
        case window = "WINDOW"
        case door = "DOOR"
        case other = "OTHER"
    }
    public var id: String?
    public var name: String?
    public var zones: [String]?
    public var type: ModelType?
    public var description: String?
    public var rooms: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["zones"] = self.zones?.encodeToJSON()
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["description"] = self.description
        nillableDictionary["rooms"] = self.rooms?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

