//
// SoundZone.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SoundZone: JSONEncodable {

    public var id: Int32?
    public var name: String?
    public var description: String?
    public var address: String?
    public var zoneType: Int32?
    public var zone: String?
    public var rooms: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["address"] = self.address
        nillableDictionary["zoneType"] = self.zoneType?.encodeToJSON()
        nillableDictionary["zone"] = self.zone
        nillableDictionary["rooms"] = self.rooms?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

