//
// SoundSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SoundSummary: JSONEncodable {

    public var zones: [SoundZone]?
    public var defaultZone: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["zones"] = self.zones?.encodeToJSON()
        nillableDictionary["defaultZone"] = self.defaultZone

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

