//
// SoundZoneStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** status of a single sound zone */
open class SoundZoneStatus: JSONEncodable {

    public var id: String?
    public var name: String?
    public var address: String?
    public var currentTrack: ActiveTrack?
    public var status: String?
    public var volume: Int32?
    public var currentPlayMode: String?
    public var nextTrack: Track?
    public var relTime: Int32?
    public var stateTime: Int64?
    public var mute: Bool?
    public var trackNo: Int32?
    public var currentState: String?
    public var zone: String?
    public var rooms: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["address"] = self.address
        nillableDictionary["currentTrack"] = self.currentTrack?.encodeToJSON()
        nillableDictionary["status"] = self.status
        nillableDictionary["volume"] = self.volume?.encodeToJSON()
        nillableDictionary["currentPlayMode"] = self.currentPlayMode
        nillableDictionary["nextTrack"] = self.nextTrack?.encodeToJSON()
        nillableDictionary["relTime"] = self.relTime?.encodeToJSON()
        nillableDictionary["stateTime"] = self.stateTime?.encodeToJSON()
        nillableDictionary["mute"] = self.mute
        nillableDictionary["trackNo"] = self.trackNo?.encodeToJSON()
        nillableDictionary["currentState"] = self.currentState
        nillableDictionary["zone"] = self.zone
        nillableDictionary["rooms"] = self.rooms?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

