//
// TemperatureZoneHistory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemperatureZoneHistory: Codable {

    public var zone: String?
    public var values: [TemperatureZoneItem]?

    public init(zone: String?, values: [TemperatureZoneItem]?) {
        self.zone = zone
        self.values = values
    }


}

