//
// WeatherForecast.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class WeatherForecast: JSONEncodable {

    public var summary: String?
    public var description: String?
    public var icon: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["summary"] = self.summary
        nillableDictionary["description"] = self.description
        nillableDictionary["icon"] = self.icon

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

