//
// EventsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class EventsAPI {
    /**
     Adds a new event to the system
     
     - parameter event: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addEvent(event: Event, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        addEventWithRequestBuilder(event: event).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Adds a new event to the system
     - POST /events
     
     - parameter event: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func addEventWithRequestBuilder(event: Event) -> RequestBuilder<Void> {
        let path = "/events"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: event)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Tests criteria
     
     - parameter criteria: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func testCriteria(criteria: [JSONValue]? = nil, completion: @escaping ((_ data: JSONValue?,_ error: Error?) -> Void)) {
        testCriteriaWithRequestBuilder(criteria: criteria).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Tests criteria
     - POST /events/criteriaTest
     - examples: [{contentType=application/json, example={
  "bytes": [
    123,
    125
  ],
  "empty": false
}}]
     
     - parameter criteria: (body)  (optional)

     - returns: RequestBuilder<JSONValue> 
     */
    open class func testCriteriaWithRequestBuilder(criteria: [JSONValue]? = nil) -> RequestBuilder<JSONValue> {
        let path = "/events/criteriaTest"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: criteria)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<JSONValue>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
