//
// ZonesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ZonesAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getZones(completion: @escaping ((_ data: [String]?,_ error: Error?) -> Void)) {
        getZonesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /zones
     - examples: [{contentType=application/json, example={}}]

     - returns: RequestBuilder<[String]> 
     */
    open class func getZonesWithRequestBuilder() -> RequestBuilder<[String]> {
        let path = "/zones"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[String]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     * enum for parameter state
     */
    public enum State_setZoneLightingState: String { 
        case on = "on"
        case off = "off"
    }

    /**

     - parameter zoneId: (path) The zone identifier, for example &#x60;living-room&#x60; 
     - parameter state: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func setZoneLightingState(zoneId: String, state: State_setZoneLightingState, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        setZoneLightingStateWithRequestBuilder(zoneId: zoneId, state: state).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /zones/{zoneId}/setLighting/{state}
     
     - parameter zoneId: (path) The zone identifier, for example &#x60;living-room&#x60; 
     - parameter state: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func setZoneLightingStateWithRequestBuilder(zoneId: String, state: State_setZoneLightingState) -> RequestBuilder<Void> {
        var path = "/zones/{zoneId}/setLighting/{state}"
        let zoneIdPreEscape = "\(zoneId)"
        let zoneIdPostEscape = zoneIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{zoneId}", with: zoneIdPostEscape, options: .literal, range: nil)
        let statePreEscape = "\(state.rawValue)"
        let statePostEscape = statePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{state}", with: statePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
